spring.application.name=schoolapp
server.port=9009
#server.servlet.context-path=/api
# Database URL
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl

# Database username & password
spring.datasource.username=C##jyoti
spring.datasource.password=jyoti

# Oracle Driver
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate Dialect (IMPORTANT)
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Show SQL queries (optional)
spring.jpa.show-sql=true

# Format SQL (optional)
spring.jpa.properties.hibernate.format_sql=true

# Auto DDL (use carefully)
spring.jpa.hibernate.ddl-auto=update
